version: "3"

services:
  db:
    image: postgres:10.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: app
    ports:
      - 15432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  db-test:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - db_test_data:/var/lib/postgresql/data

  php:
    build:
      context: ./api
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./api:/var/www/html
      - ./api/docker/php/php.ini:/usr/local/etc/php/php.ini
      - ~/.composer:/root/.composer

  horizon:
    build:
      context: ./api
      dockerfile: ./docker/laravel-horizon/Dockerfile
    command: /usr/bin/env php artisan horizon
    volumes:
      - ./api:/var/www/html

  echo:
    build:
      context: ./echo
      dockerfile: ./Dockerfile
    volumes:
      - ./echo/laravel-echo-server.json:/var/www/html/laravel-echo-server.json

  nginx:
    image: nginx:alpine
    volumes:
      - ./api:/var/www/html
      - ./front/nginx/www.conf:/etc/nginx/conf.d/default.conf
      - ./front/docs:/var/www/html/docs
      - ./front/node_modules/redoc/bundles:/var/www/html/docs/redoc/bundles
    working_dir: /var/www/html
    ports:
      - 8080:80

  redis:
    image: redis:alpine
    command: --requirepass $REDIS_PASSWORD

volumes:
  db_data:
  db_test_data:
